#!/bin/bash

# Copyright (c) 2011 Alexey I. Froloff.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. /etc/init.d/functions

cd /etc/sysconfig/network-scripts
. ./network-functions

[ -f ../network ] && . ../network

CONFIG=${1}

need_config ${CONFIG}

source_config

case "$TYPE" in
        IVSIntPort)
                intf=$(ivs-ctl list-ports | grep "$DEVICE")
                if [ -z $intf ]; then
                    ivs-ctl add-internal-port "$DEVICE"
                fi
                ifconfig "$DEVICE" "$IPADDR" netmask "$NETMASK"
                ;;
        *)
                intf=$(ivs-ctl list-ports | grep "$DEVICE")
                if [ -z $intf ]; then
                    /sbin/ip link set dev ${DEVICE} up
                    ivs-ctl add-port "$DEVICE"
                fi
                ;;
esac

